GET http://localhost:4000/api/users HTTP/1.1
###

POST http://localhost:4000/api/signup HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "username": "Maria",
    "email": "mariacarmen28@example.com",
    "password": "conyyesddw",
    "cedula": "12345778901"
}
###
POST http://localhost:4000/api/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "mariacarmen28@example.com",
    "password": "conyyesddw"
}

###
DELETE http://localhost:4000/api/delete/68606d8618be6649b483f882 HTTP/1.1
Content-Type: application/json
